// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBJvZX1xWTHq1ScDYZuVYasZT0h8nW7q4',
    appId: '1:469888334604:web:8415796d32ff81a974a729',
    messagingSenderId: '469888334604',
    projectId: 'flutter-chat-app-65a5e',
    authDomain: 'flutter-chat-app-65a5e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-65a5e.appspot.com',
    measurementId: 'G-2HYLC3N2LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvZSa_znE6UT1RgtAo4rsAOD3LnwXL5l4',
    appId: '1:469888334604:android:7538ca3c877c5d0274a729',
    messagingSenderId: '469888334604',
    projectId: 'flutter-chat-app-65a5e',
    storageBucket: 'flutter-chat-app-65a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC90BfeH1RyCfbki7UqbJ9x7vEyrRkvAA',
    appId: '1:469888334604:ios:636ed876801e301974a729',
    messagingSenderId: '469888334604',
    projectId: 'flutter-chat-app-65a5e',
    storageBucket: 'flutter-chat-app-65a5e.appspot.com',
    iosClientId: '469888334604-90hpojgvfsqrmsrca7irtipc0r3kkemq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC90BfeH1RyCfbki7UqbJ9x7vEyrRkvAA',
    appId: '1:469888334604:ios:4a0590952b226e3a74a729',
    messagingSenderId: '469888334604',
    projectId: 'flutter-chat-app-65a5e',
    storageBucket: 'flutter-chat-app-65a5e.appspot.com',
    iosClientId: '469888334604-gbdtvjn33h00ck7fmiilcfkl7uv1ini3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
